-- 코드를 입력하세요
# SELECT J.FLAVOR, F.TOTAL_ORDER, J.TOTAL_ORDER
# FROM (
    SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        
    # ) F
#     JOIN 
#     (SELECT FLAVOR, TOTAL_ORDER
#         FROM JULY 
#         GROUP BY FLAVOR
#     ) J
# )
# ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER DESC
# LIMIT 3