-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
INNER JOIN (
    SELECT FLAVOR, sum(TOTAL_ORDER) AS TR
    FROM JULY
    GROUP BY FLAVOR
) J
ON F.FLAVOR = J.FLAVOR
ORDER BY (TOTAL_ORDER + TR) DESC
LIMIT 3