# -- 코드를 입력하세요
WITH RECURSIVE cte (DATETIME) AS (
	SELECT 0 
	UNION ALL
	SELECT DATETIME + 1 FROM cte WHERE DATETIME < 23
) 
 
SELECT C.DATETIME AS 'HOUR', IFNULL(COUNT(A.ANIMAL_ID), 0) AS 'COUNT'
from cte C
LEFT JOIN ANIMAL_OUTS A
ON HOUR(A.DATETIME) = C.DATETIME
GROUP BY 1
ORDER BY 1
