-- 코드를 작성해주세요
SELECT distinct(ID), EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, SKILLCODES
WHERE 
(SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') & DEVELOPERS.SKILL_CODE
OR
(SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') & DEVELOPERS.SKILL_CODE
ORDER BY ID