-- 코드를 입력하세요
SELECT distinct(I.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR I
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON I.CAR_ID = H.CAR_ID
WHERE I.CAR_TYPE = '세단'
AND MONTH(H.START_DATE) = 10
ORDER BY I.CAR_ID DESC