-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
LEFT JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH in 
(SELECT MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE HAVING FISH_TYPE = N.FISH_TYPE)
ORDER BY I.ID;